### ISSUE TITLE
Модуль bepaid

### ISSUE THREAD

**Issue by IvanVasilchikov** [begateway/opencart-2.1-payment-module#2]
ДОбрый день!
Поставили модуль на CMS Opencart - a-ir.by. В тестовом режиме с тестовыми данными все хорошо работало.
Когда в тестовый режим поставили реальные данные - модуль начал виснуть в корзине. Нажимаем кнопку отправить заказ и все зависает.
Помогите плиз решить проблему.

**Comment by avsh** [comment]
Не заметил ваш запрос в спам папке уведомлений. Если проблема еще актуальна, то в модуле поменяйте параметры:
Домен платежного шлюза на gateway.bepaid.by
Домен страницы оплаты на checkout.bepaid.by
